name: CI

on:
  push:
    branches:
      - master

jobs:

 example_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Files in Workspace
        run: |
          # Use the 'ls' command to list files/folders in the workspace directory
          # You can replace 'workspace' with the specific directory you want to list
          folder_list=$(ls -1 lib)

          # Print the list for verification
          echo "Folder List:"
          echo "$folder_list"

          echo "FOLDER_LIST=${folder_list}" >> $GITHUB_ENV
          
        shell: bash
        
      - name: Set Output in Job 1
        id: job1-output
        run: echo "::set-output name=folder_list::$MY_VARIABLE"
        
      - name: Use the Environment Variable
        run: |
          # Access the environment variable in subsequent steps
          echo "Folder List from Environment Variable:"
          echo "$FOLDER_LIST"


 other_job:
    needs: example_matrix
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use the Environment Variable
        run: |
          # Access the environment variable in subsequent steps
          echo "Folder List from Environment Variable:"
          echo "$FOLDER_LIST"


            

