name: 🧪 Test with coverage 📊

on:
  workflow_call:

jobs:
  coverage:
    name: 🧪 Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
     - name: Flutter SDK
        # You may pin to the exact commit or the version.
          # uses: MobileDevOps/flutter-sdk-action@a93694305106b954a8b85195ab7cd4bfec0401bf
       uses: MobileDevOps/flutter-sdk-action@v1.0.0
          with:
            # The Flutter SDK Version
       flutter-sdk-version: # optional, default is stable
