name: CI

on:
  push:
    branches:
      - master

jobs:

 other_job:
    strategy:
      matrix:
        version: ["blue","yello"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use the Environment Variable
        run: |
          # Access the environment variable in subsequent steps
          echo "/test/${{ matrix.os }}"
          echo "$FOLDER_LIST"


            

